Repository pre-onboarding-frontend-7-team-3/pre-onboarding-7th-2-2-3, pull requests merged in 2022-11, with the labels that each got.

#10 [ Refactor ] : AdManagement 데이터 store에서 관리
  .eslintcache
  db.json
  public/mock/adListData.json
  src/components/AdManagement/AdManagementHeader.js
  src/components/card/CardList.jsx
  src/store/atoms/cards.js
Labels: refactor

#12 [ Style ] migrate to styled-components
  .eslintcache
  package-lock.json
  package.json
  src/App.jsx
  src/components/AdManagement/AdManagementHeader.js
  src/components/AdManagement/AdManagementHeader.jsx
  src/components/AdManagement/DateRangeModal.jsx
  src/components/Home/CompareGraph/CompareGraph.jsx
  src/components/common/Header.js
  src/components/common/PageHeader.jsx
  src/components/common/SEO.jsx
  src/constants/AdManagementSelectData.js
  src/index.jsx
  src/shared/GlobalStyle.js
  src/shared/theme.js
  src/store/atoms/cards.js
Labels: style

#13 [FEAT] Layout
  .env.production
  package-lock.json
  package.json
  public/LEVER_LOGO.png
  server/db.json
  server/index.js
  src/App.jsx
  src/components/Layout/LayoutHeader/index.jsx
  src/components/Layout/LayoutNav/NavAdCenter.jsx
  src/components/Layout/LayoutNav/NavFooter.jsx
  src/components/Layout/LayoutNav/NavGuide.jsx
  src/components/Layout/LayoutNav/NavService.jsx
  src/components/Layout/LayoutNav/index.jsx
  src/components/Layout/index.jsx
  src/components/common/Icon.jsx
  src/components/common/icons/Alarm.js
  src/components/common/icons/DashBoard.js
  src/components/common/icons/DefaultUser.js
  src/components/common/icons/Guide.js
  src/components/common/icons/ManageAds.js
  src/components/common/icons/Setting.js
  src/components/common/icons/SideNavToggle.js
  src/components/common/icons/index.js
  src/constants/AdCenterType.js
  src/hooks/AdManagement/useOnClickOutside.js
Labels: Feat

#15 [ Feat ] SEO 컴포넌트 / suspense / 컴포넌트 간 간격 수정
  .eslintcache
  package-lock.json
  package.json
  src/App.jsx
  src/apis/cardsApi.js
  src/components/AdManagement/AdManagementHeader.jsx
  src/components/Home/ComparePerformance/ComparePerformance.jsx
  src/components/Home/ComparePerformance/InfoBoxes.jsx
  src/components/Layout/LayoutHeader/index.jsx
  src/components/card/CardList.jsx
  src/components/common/PageHeader.jsx
  src/pages/AdManagement/AdManagement.jsx
  src/pages/AdManagement/index.js
  src/pages/Home/Home.jsx
  src/store/atoms/cards.js
  src/store/atoms/data.js
  src/styles/GlobalStyles.js
  src/styles/theme.js
Labels: Feat

#17 [ Feat ] 페이지 간 로딩 지연 처리 - useLoading hook
  .eslintcache
  package-lock.json
  package.json
  src/App.jsx
  src/components/AdManagement/AdManagementHeader.jsx
  src/components/Home/CompareGraph/CompareGraph.jsx
  src/components/Home/ComparePerformance/ComparePerformance.jsx
  src/components/Layout/LayoutHeader/index.jsx
  src/components/Layout/LayoutNav/NavAdCenter.jsx
  src/components/Layout/LayoutNav/NavFooter.jsx
  src/components/Layout/LayoutNav/NavGuide.jsx
  src/components/Layout/LayoutNav/NavService.jsx
  src/components/Layout/LayoutNav/index.jsx
  src/components/Layout/index.jsx
  src/components/card/CardList.jsx
  src/components/common/PageHeader.jsx
  src/components/common/Spinner.js
  src/hooks/AdManagement/useEndDate.js
  src/hooks/AdManagement/useStartDate.js
  src/hooks/useLoading.js
  src/pages/AdManagement/AdManagement.jsx
  src/shared/theme.js
  src/store/adList.js
  src/store/addFilter.js
  src/store/date.js
  src/store/graphNav.js
  src/store/trend.js
Labels: Feat

#18 [ Feat ] : Date Range Modal 메인 페이지에서만 렌더링 조건 추가
  .eslintcache
  public/index.html
  src/components/common/PageHeader.jsx
  src/pages/AdManagement/AdManagement.jsx
  src/pages/Home/Home.jsx
Labels: Feat
